import { Product } from './types';
import { getProductImage } from './lib/imageMapping';

export const INITIAL_PRODUCTS: Omit<Product, 'id'>[] = [
  // Fruits (25 items)
  {
    name: 'Premium Alphonso Mangoes',
    description: 'Sweet and juicy Alphonso mangoes from local Telangana orchards.',
    price: 450,
    category: 'Fruits',
    imageUrl: getProductImage('Premium Alphonso Mangoes', 'Fruits'),
    unit: '1 Dozen',
    stock: 50,
    isOrganic: true,
  },
  {
    name: 'Organic Cavendish Bananas',
    description: 'Naturally ripened organic bananas from Telangana.',
    price: 60,
    category: 'Fruits',
    imageUrl: getProductImage('Organic Cavendish Bananas', 'Fruits'),
    unit: '1 Dozen',
    stock: 80,
    isOrganic: true,
  },
  {
    name: 'Red Delicious Apples',
    description: 'Crisp and sweet premium red apples.',
    price: 180,
    category: 'Fruits',
    imageUrl: getProductImage('Red Delicious Apples', 'Fruits'),
    unit: '1 kg',
    stock: 100,
    isOrganic: false,
  },
  {
    name: 'Green Grapes (Seedless)',
    description: 'Sweet and crunchy seedless green grapes.',
    price: 120,
    category: 'Fruits',
    imageUrl: getProductImage('Green Grapes (Seedless)', 'Fruits'),
    unit: '500g',
    stock: 60,
    isOrganic: false,
  },
  {
    name: 'Pomegranate (Anar)',
    description: 'Rich in antioxidants, premium quality pomegranates.',
    price: 220,
    category: 'Fruits',
    imageUrl: getProductImage('Pomegranate (Anar)', 'Fruits'),
    unit: '1 kg',
    stock: 40,
    isOrganic: false,
  },
  {
    name: 'Fresh Papaya',
    description: 'Sweet and ripe papaya, perfect for breakfast.',
    price: 50,
    category: 'Fruits',
    imageUrl: getProductImage('Fresh Papaya', 'Fruits'),
    unit: '1 pc',
    stock: 70,
    isOrganic: false,
  },
  {
    name: 'Watermelon (Kalinga)',
    description: 'Hydrating and sweet large watermelons.',
    price: 40,
    category: 'Fruits',
    imageUrl: getProductImage('Watermelon (Kalinga)', 'Fruits'),
    unit: '1 pc',
    stock: 50,
    isOrganic: false,
  },
  {
    name: 'Muskmelon',
    description: 'Fragrant and sweet muskmelons.',
    price: 60,
    category: 'Fruits',
    imageUrl: getProductImage('Muskmelon', 'Fruits'),
    unit: '1 pc',
    stock: 45,
    isOrganic: false,
  },
  {
    name: 'Guava (Amrud)',
    description: 'Fresh and crunchy local guavas.',
    price: 80,
    category: 'Fruits',
    imageUrl: getProductImage('Guava (Amrud)', 'Fruits'),
    unit: '1 kg',
    stock: 90,
    isOrganic: false,
  },
  {
    name: 'Sweet Lime (Mosambi)',
    description: 'Juicy sweet limes, perfect for fresh juice.',
    price: 110,
    category: 'Fruits',
    imageUrl: getProductImage('Sweet Lime (Mosambi)', 'Fruits'),
    unit: '1 kg',
    stock: 120,
    isOrganic: false,
  },
  {
    name: 'Orange (Nagpur)',
    description: 'Tangy and sweet Nagpur oranges.',
    price: 140,
    category: 'Fruits',
    imageUrl: getProductImage('Orange (Nagpur)', 'Fruits'),
    unit: '1 kg',
    stock: 85,
    isOrganic: false,
  },
  {
    name: 'Pineapple',
    description: 'Sweet and tart tropical pineapples.',
    price: 70,
    category: 'Fruits',
    imageUrl: getProductImage('Pineapple', 'Fruits'),
    unit: '1 pc',
    stock: 35,
    isOrganic: false,
  },
  {
    name: 'Pear (Naspati)',
    description: 'Crunchy and sweet local pears.',
    price: 160,
    category: 'Fruits',
    imageUrl: getProductImage('Pear (Naspati)', 'Fruits'),
    unit: '1 kg',
    stock: 55,
    isOrganic: false,
  },
  {
    name: 'Sapota (Chiku)',
    description: 'Sweet and grainy sapotas from local farms.',
    price: 90,
    category: 'Fruits',
    imageUrl: getProductImage('Sapota (Chiku)', 'Fruits'),
    unit: '1 kg',
    stock: 110,
    isOrganic: false,
  },
  {
    name: 'Custard Apple (Sitaphal)',
    description: 'Creamy and sweet seasonal custard apples.',
    price: 150,
    category: 'Fruits',
    imageUrl: getProductImage('Custard Apple (Sitaphal)', 'Fruits'),
    unit: '1 kg',
    stock: 40,
    isOrganic: false,
  },
  {
    name: 'Black Grapes',
    description: 'Sweet and juicy black seedless grapes.',
    price: 140,
    category: 'Fruits',
    imageUrl: getProductImage('Black Grapes', 'Fruits'),
    unit: '500g',
    stock: 50,
    isOrganic: false,
  },
  {
    name: 'Plums',
    description: 'Tart and sweet fresh plums.',
    price: 240,
    category: 'Fruits',
    imageUrl: getProductImage('Plums', 'Fruits'),
    unit: '500g',
    stock: 30,
    isOrganic: false,
  },
  {
    name: 'Peach',
    description: 'Soft and sweet fresh peaches.',
    price: 280,
    category: 'Fruits',
    imageUrl: getProductImage('Peach', 'Fruits'),
    unit: '500g',
    stock: 25,
    isOrganic: false,
  },
  {
    name: 'Apricot',
    description: 'Velvety and sweet fresh apricots.',
    price: 320,
    category: 'Fruits',
    imageUrl: getProductImage('Apricot', 'Fruits'),
    unit: '250g',
    stock: 20,
    isOrganic: false,
  },
  {
    name: 'Cherry',
    description: 'Sweet and tart premium cherries.',
    price: 450,
    category: 'Fruits',
    imageUrl: getProductImage('Cherry', 'Fruits'),
    unit: '250g',
    stock: 15,
    isOrganic: false,
  },
  {
    name: 'Strawberry',
    description: 'Fresh and sweet red strawberries.',
    price: 120,
    category: 'Fruits',
    imageUrl: getProductImage('Strawberry', 'Fruits'),
    unit: '200g',
    stock: 45,
    isOrganic: false,
  },
  {
    name: 'Blueberry',
    description: 'Antioxidant-rich fresh blueberries.',
    price: 350,
    category: 'Fruits',
    imageUrl: getProductImage('Blueberry', 'Fruits'),
    unit: '125g',
    stock: 20,
    isOrganic: false,
  },
  {
    name: 'Raspberry',
    description: 'Delicate and sweet fresh raspberries.',
    price: 380,
    category: 'Fruits',
    imageUrl: getProductImage('Raspberry', 'Fruits'),
    unit: '125g',
    stock: 15,
    isOrganic: false,
  },
  {
    name: 'Blackberry',
    description: 'Plump and sweet fresh blackberries.',
    price: 380,
    category: 'Fruits',
    imageUrl: getProductImage('Blackberry', 'Fruits'),
    unit: '125g',
    stock: 15,
    isOrganic: false,
  },
  {
    name: 'Kiwi (Green)',
    description: 'Tangy and nutrient-rich green kiwis.',
    price: 140,
    category: 'Fruits',
    imageUrl: getProductImage('Kiwi (Green)', 'Fruits'),
    unit: '3 pcs',
    stock: 60,
    isOrganic: false,
  },

  // Vegetables (30 items)
  {
    name: 'Premium Red Onions',
    description: 'Crisp and pungent red onions, essential for Indian cooking.',
    price: 40,
    category: 'Vegetables',
    imageUrl: getProductImage('Premium Red Onions', 'Vegetables'),
    unit: '1 kg',
    stock: 200,
    isOrganic: false,
  },
  {
    name: 'Vine-Ripened Tomatoes',
    description: 'Vine-ripened juicy tomatoes from local farms.',
    price: 35,
    category: 'Vegetables',
    imageUrl: getProductImage('Vine-Ripened Tomatoes', 'Vegetables'),
    unit: '1 kg',
    stock: 150,
    isOrganic: false,
  },
  {
    name: 'Fresh Lady Finger (Bhindi)',
    description: 'Tender and fresh lady fingers.',
    price: 50,
    category: 'Vegetables',
    imageUrl: getProductImage('Fresh Lady Finger (Bhindi)', 'Vegetables'),
    unit: '500g',
    stock: 90,
    isOrganic: false,
  },
  {
    name: 'Potatoes (Jyoti)',
    description: 'High-quality potatoes, perfect for all recipes.',
    price: 30,
    category: 'Vegetables',
    imageUrl: getProductImage('Potatoes (Jyoti)', 'Vegetables'),
    unit: '1 kg',
    stock: 300,
    isOrganic: false,
  },
  {
    name: 'Carrots (Local)',
    description: 'Crunchy and sweet local carrots.',
    price: 60,
    category: 'Vegetables',
    imageUrl: getProductImage('Carrots (Local)', 'Vegetables'),
    unit: '500g',
    stock: 120,
    isOrganic: false,
  },
  {
    name: 'Cauliflower',
    description: 'Fresh and white cauliflower heads.',
    price: 40,
    category: 'Vegetables',
    imageUrl: getProductImage('Cauliflower', 'Vegetables'),
    unit: '1 pc',
    stock: 80,
    isOrganic: false,
  },
  {
    name: 'Cabbage',
    description: 'Crisp and fresh green cabbage.',
    price: 30,
    category: 'Vegetables',
    imageUrl: getProductImage('Cabbage', 'Vegetables'),
    unit: '1 pc',
    stock: 100,
    isOrganic: false,
  },
  {
    name: 'Green Peas',
    description: 'Fresh and sweet green peas in pods.',
    price: 120,
    category: 'Vegetables',
    imageUrl: getProductImage('Green Peas', 'Vegetables'),
    unit: '500g',
    stock: 50,
    isOrganic: false,
  },
  {
    name: 'French Beans',
    description: 'Tender and fresh French beans.',
    price: 80,
    category: 'Vegetables',
    imageUrl: getProductImage('French Beans', 'Vegetables'),
    unit: '500g',
    stock: 70,
    isOrganic: false,
  },
  {
    name: 'Capsicum (Green)',
    description: 'Fresh and crunchy green capsicums.',
    price: 60,
    category: 'Vegetables',
    imageUrl: getProductImage('Capsicum (Green)', 'Vegetables'),
    unit: '500g',
    stock: 90,
    isOrganic: false,
  },
  {
    name: 'Brinjal (Small)',
    description: 'Tender small brinjals, perfect for stuffing.',
    price: 40,
    category: 'Vegetables',
    imageUrl: getProductImage('Brinjal (Small)', 'Vegetables'),
    unit: '500g',
    stock: 110,
    isOrganic: false,
  },
  {
    name: 'Bottle Gourd (Lauki)',
    description: 'Fresh and tender bottle gourds.',
    price: 30,
    category: 'Vegetables',
    imageUrl: getProductImage('Bottle Gourd (Lauki)', 'Vegetables'),
    unit: '1 pc',
    stock: 85,
    isOrganic: false,
  },
  {
    name: 'Bitter Gourd (Karela)',
    description: 'Fresh and firm bitter gourds.',
    price: 50,
    category: 'Vegetables',
    imageUrl: getProductImage('Bitter Gourd (Karela)', 'Vegetables'),
    unit: '500g',
    stock: 65,
    isOrganic: false,
  },
  {
    name: 'Ridge Gourd (Turai)',
    description: 'Fresh and tender ridge gourds.',
    price: 45,
    category: 'Vegetables',
    imageUrl: getProductImage('Ridge Gourd (Turai)', 'Vegetables'),
    unit: '500g',
    stock: 75,
    isOrganic: false,
  },
  {
    name: 'Cucumber (Local)',
    description: 'Cool and crunchy local cucumbers.',
    price: 40,
    category: 'Vegetables',
    imageUrl: getProductImage('Cucumber (Local)', 'Vegetables'),
    unit: '500g',
    stock: 130,
    isOrganic: false,
  },
  {
    name: 'Ginger',
    description: 'Fresh and aromatic ginger roots.',
    price: 180,
    category: 'Vegetables',
    imageUrl: getProductImage('Ginger', 'Vegetables'),
    unit: '250g',
    stock: 100,
    isOrganic: false,
  },
  {
    name: 'Garlic',
    description: 'Premium quality garlic bulbs.',
    price: 220,
    category: 'Vegetables',
    imageUrl: getProductImage('Garlic', 'Vegetables'),
    unit: '250g',
    stock: 90,
    isOrganic: false,
  },
  {
    name: 'Green Chillies',
    description: 'Spicy and fresh green chillies.',
    price: 30,
    category: 'Vegetables',
    imageUrl: getProductImage('Green Chillies', 'Vegetables'),
    unit: '100g',
    stock: 150,
    isOrganic: false,
  },
  {
    name: 'Lemon',
    description: 'Juicy and fresh lemons.',
    price: 40,
    category: 'Vegetables',
    imageUrl: getProductImage('Lemon', 'Vegetables'),
    unit: '250g',
    stock: 200,
    isOrganic: false,
  },
  {
    name: 'Sweet Potato',
    description: 'Nutritious and sweet potatoes.',
    price: 60,
    category: 'Vegetables',
    imageUrl: getProductImage('Sweet Potato', 'Vegetables'),
    unit: '1 kg',
    stock: 80,
    isOrganic: false,
  },
  {
    name: 'Beetroot',
    description: 'Fresh and earthy beetroots.',
    price: 50,
    category: 'Vegetables',
    imageUrl: getProductImage('Beetroot', 'Vegetables'),
    unit: '500g',
    stock: 95,
    isOrganic: false,
  },
  {
    name: 'Radish (White)',
    description: 'Crunchy and pungent white radishes.',
    price: 30,
    category: 'Vegetables',
    imageUrl: getProductImage('Radish (White)', 'Vegetables'),
    unit: '500g',
    stock: 85,
    isOrganic: false,
  },
  {
    name: 'Pumpkin',
    description: 'Fresh and sweet pumpkins.',
    price: 40,
    category: 'Vegetables',
    imageUrl: getProductImage('Pumpkin', 'Vegetables'),
    unit: '1 kg',
    stock: 60,
    isOrganic: false,
  },
  {
    name: 'Drumstick',
    description: 'Fresh and tender drumsticks.',
    price: 40,
    category: 'Vegetables',
    imageUrl: getProductImage('Drumstick', 'Vegetables'),
    unit: '250g',
    stock: 70,
    isOrganic: false,
  },
  {
    name: 'Colocasia (Arbi)',
    description: 'High-quality colocasia roots.',
    price: 60,
    category: 'Vegetables',
    imageUrl: getProductImage('Colocasia (Arbi)', 'Vegetables'),
    unit: '500g',
    stock: 55,
    isOrganic: false,
  },
  {
    name: 'Yam (Suran)',
    description: 'Fresh and firm elephant foot yam.',
    price: 80,
    category: 'Vegetables',
    imageUrl: getProductImage('Yam (Suran)', 'Vegetables'),
    unit: '1 kg',
    stock: 45,
    isOrganic: false,
  },
  {
    name: 'Broccoli',
    description: 'Nutrient-dense fresh broccoli.',
    price: 120,
    category: 'Vegetables',
    imageUrl: getProductImage('Broccoli', 'Vegetables'),
    unit: '1 pc',
    stock: 40,
    isOrganic: false,
  },
  {
    name: 'Mushroom (Button)',
    description: 'Fresh and white button mushrooms.',
    price: 60,
    category: 'Vegetables',
    imageUrl: getProductImage('Mushroom (Button)', 'Vegetables'),
    unit: '200g',
    stock: 50,
    isOrganic: false,
  },
  {
    name: 'Sweet Corn',
    description: 'Sweet and tender corn on the cob.',
    price: 30,
    category: 'Vegetables',
    imageUrl: getProductImage('Sweet Corn', 'Vegetables'),
    unit: '1 pc',
    stock: 120,
    isOrganic: false,
  },
  {
    name: 'Baby Corn',
    description: 'Tender and fresh baby corn.',
    price: 60,
    category: 'Vegetables',
    imageUrl: getProductImage('Baby Corn', 'Vegetables'),
    unit: '200g',
    stock: 60,
    isOrganic: false,
  },

  // Leafy Greens
  {
    name: 'Organic Spinach (Palak)',
    description: 'Freshly harvested organic spinach leaves, rich in iron.',
    price: 30,
    category: 'Leafy Greens',
    imageUrl: getProductImage('Organic Spinach (Palak)', 'Leafy Greens'),
    unit: '1 Bunch',
    stock: 100,
    isOrganic: true,
  },
  {
    name: 'Fresh Coriander (Kothmir)',
    description: 'Aromatic fresh coriander leaves for garnishing.',
    price: 15,
    category: 'Leafy Greens',
    imageUrl: getProductImage('Fresh Coriander (Kothmir)', 'Leafy Greens'),
    unit: '1 Bunch',
    stock: 120,
    isOrganic: false,
  },
  {
    name: 'Fenugreek (Methi)',
    description: 'Fresh and bitter-sweet fenugreek leaves.',
    price: 25,
    category: 'Leafy Greens',
    imageUrl: getProductImage('Fenugreek (Methi)', 'Leafy Greens'),
    unit: '1 Bunch',
    stock: 80,
    isOrganic: false,
  },
  {
    name: 'Mint Leaves (Pudina)',
    description: 'Fresh and aromatic mint leaves.',
    price: 20,
    category: 'Leafy Greens',
    imageUrl: getProductImage('Mint Leaves (Pudina)', 'Leafy Greens'),
    unit: '1 Bunch',
    stock: 150,
    isOrganic: false,
  },

  // Exotic Fruits
  {
    name: 'Dragon Fruit (Pink)',
    description: 'Vibrant and nutrient-rich exotic dragon fruit.',
    price: 120,
    category: 'Exotic Fruits',
    imageUrl: getProductImage('Dragon Fruit (Pink)', 'Exotic Fruits'),
    unit: '1 pc',
    stock: 30,
    isOrganic: false,
  },
  {
    name: 'Avocado (Hass)',
    description: 'Creamy and rich premium Hass avocados.',
    price: 250,
    category: 'Exotic Fruits',
    imageUrl: getProductImage('Avocado (Hass)', 'Exotic Fruits'),
    unit: '1 pc',
    stock: 25,
    isOrganic: false,
  },
  {
    name: 'Passion Fruit',
    description: 'Fragrant and tart exotic passion fruit.',
    price: 180,
    category: 'Exotic Fruits',
    imageUrl: getProductImage('Passion Fruit', 'Exotic Fruits'),
    unit: '250g',
    stock: 20,
    isOrganic: false,
  },

  // Organic Products
  {
    name: 'Organic Carrots',
    description: 'Crunchy and sweet organic carrots.',
    price: 80,
    category: 'Organic Products',
    imageUrl: getProductImage('Organic Carrots', 'Organic Products'),
    unit: '500g',
    stock: 60,
    isOrganic: true,
  },
  {
    name: 'Organic Honey',
    description: 'Pure and raw organic honey from forest hives.',
    price: 450,
    category: 'Organic Products',
    imageUrl: getProductImage('Organic Honey', 'Organic Products'),
    unit: '500g',
    stock: 40,
    isOrganic: true,
  },

  // Dairy (7 items)
  {
    name: 'Fresh Whole Milk',
    description: 'Farm-fresh whole milk, pasteurized and homogenized.',
    price: 65,
    category: 'Dairy',
    imageUrl: getProductImage('Fresh Whole Milk', 'Dairy'),
    unit: '1 L',
    stock: 100,
    isOrganic: false,
  },
  {
    name: 'Amul Butter',
    description: 'Classic salted butter for your daily needs.',
    price: 55,
    category: 'Dairy',
    imageUrl: getProductImage('Amul Butter', 'Dairy'),
    unit: '100g',
    stock: 200,
    isOrganic: false,
  },
  {
    name: 'Cheddar Cheese',
    description: 'Sharp and creamy cheddar cheese slices.',
    price: 180,
    category: 'Dairy',
    imageUrl: getProductImage('Cheddar Cheese', 'Dairy'),
    unit: '200g',
    stock: 50,
    isOrganic: false,
  },
  {
    name: 'Fresh Paneer',
    description: 'Soft and fresh cottage cheese (Paneer).',
    price: 120,
    category: 'Dairy',
    imageUrl: getProductImage('Fresh Paneer', 'Dairy'),
    unit: '200g',
    stock: 60,
    isOrganic: false,
  },
  {
    name: 'Greek Yogurt',
    description: 'Thick and creamy plain Greek yogurt.',
    price: 90,
    category: 'Dairy',
    imageUrl: getProductImage('Greek Yogurt', 'Dairy'),
    unit: '200g',
    stock: 40,
    isOrganic: false,
  },
  {
    name: 'Pure Cow Ghee',
    description: 'Traditional clarified butter made from cow milk.',
    price: 650,
    category: 'Dairy',
    imageUrl: getProductImage('Pure Cow Ghee', 'Dairy'),
    unit: '500ml',
    stock: 30,
    isOrganic: true,
  },
  {
    name: 'Fresh Curd',
    description: 'Creamy and thick homemade style curd.',
    price: 40,
    category: 'Dairy',
    imageUrl: getProductImage('Fresh Curd', 'Dairy'),
    unit: '500g',
    stock: 80,
    isOrganic: false,
  },

  // Bakery (5 items)
  {
    name: 'Whole Wheat Bread',
    description: 'Healthy and fiber-rich whole wheat bread.',
    price: 45,
    category: 'Bakery',
    imageUrl: getProductImage('Whole Wheat Bread', 'Bakery'),
    unit: '400g',
    stock: 100,
    isOrganic: false,
  },
  {
    name: 'Brown Bread',
    description: 'Nutritious brown bread for a healthy breakfast.',
    price: 50,
    category: 'Bakery',
    imageUrl: getProductImage('Brown Bread', 'Bakery'),
    unit: '400g',
    stock: 80,
    isOrganic: false,
  },
  {
    name: 'Burger Buns',
    description: 'Soft and fresh burger buns (Pack of 2).',
    price: 35,
    category: 'Bakery',
    imageUrl: getProductImage('Burger Buns', 'Bakery'),
    unit: '1 Pack',
    stock: 60,
    isOrganic: false,
  },
  {
    name: 'Chocolate Truffle Cake',
    description: 'Rich and decadent chocolate truffle cake.',
    price: 550,
    category: 'Bakery',
    imageUrl: getProductImage('Chocolate Truffle Cake', 'Bakery'),
    unit: '500g',
    stock: 15,
    isOrganic: false,
  },
  {
    name: 'Butter Croissants',
    description: 'Flaky and buttery French-style croissants.',
    price: 120,
    category: 'Bakery',
    imageUrl: getProductImage('Butter Croissants', 'Bakery'),
    unit: 'Pack of 2',
    stock: 20,
    isOrganic: false,
  },

  // Herbs & Spices (8 items)
  {
    name: 'Fresh Ginger',
    description: 'Spicy and aromatic fresh ginger root.',
    price: 40,
    category: 'Herbs & Spices',
    imageUrl: getProductImage('Fresh Ginger', 'Herbs & Spices'),
    unit: '250g',
    stock: 100,
    isOrganic: false,
  },
  {
    name: 'Garlic (Lahsuna)',
    description: 'Pungent and flavorful fresh garlic bulbs.',
    price: 60,
    category: 'Herbs & Spices',
    imageUrl: getProductImage('Garlic (Lahsuna)', 'Herbs & Spices'),
    unit: '250g',
    stock: 90,
    isOrganic: false,
  },
  {
    name: 'Fresh Turmeric',
    description: 'Raw turmeric root, rich in curcumin.',
    price: 50,
    category: 'Herbs & Spices',
    imageUrl: getProductImage('Fresh Turmeric', 'Herbs & Spices'),
    unit: '250g',
    stock: 50,
    isOrganic: true,
  },
  {
    name: 'Green Chillies',
    description: 'Spicy and fresh green chillies.',
    price: 20,
    category: 'Herbs & Spices',
    imageUrl: getProductImage('Green Chillies', 'Herbs & Spices'),
    unit: '100g',
    stock: 150,
    isOrganic: false,
  },
  {
    name: 'Cinnamon Sticks',
    description: 'Aromatic and sweet cinnamon sticks.',
    price: 80,
    category: 'Herbs & Spices',
    imageUrl: getProductImage('Cinnamon Sticks', 'Herbs & Spices'),
    unit: '50g',
    stock: 40,
    isOrganic: false,
  },
  {
    name: 'Black Pepper',
    description: 'Whole black peppercorns, bold and spicy.',
    price: 120,
    category: 'Herbs & Spices',
    imageUrl: getProductImage('Black Pepper', 'Herbs & Spices'),
    unit: '100g',
    stock: 60,
    isOrganic: false,
  },
  {
    name: 'Lemongrass',
    description: 'Fresh lemongrass stalks for tea and cooking.',
    price: 30,
    category: 'Herbs & Spices',
    imageUrl: getProductImage('Lemongrass', 'Herbs & Spices'),
    unit: '1 Bunch',
    stock: 50,
    isOrganic: false,
  },
  {
    name: 'Red Chilli Powder',
    description: 'Pure and spicy red chilli powder.',
    price: 90,
    category: 'Herbs & Spices',
    imageUrl: getProductImage('Red Chilli Powder', 'Herbs & Spices'),
    unit: '200g',
    stock: 100,
    isOrganic: false,
  },

  // Others (8 items)
  {
    name: 'Premium Almonds (Badam)',
    description: 'Crunchy and nutritious premium almonds.',
    price: 450,
    category: 'Others',
    imageUrl: getProductImage('Premium Almonds (Badam)', 'Others'),
    unit: '500g',
    stock: 50,
    isOrganic: false,
  },
  {
    name: 'Cashew Nuts (Kaju)',
    description: 'Creamy and sweet whole cashew nuts.',
    price: 550,
    category: 'Others',
    imageUrl: getProductImage('Cashew Nuts (Kaju)', 'Others'),
    unit: '500g',
    stock: 40,
    isOrganic: false,
  },
  {
    name: 'Walnuts (Akhrot)',
    description: 'Rich in Omega-3, premium quality walnuts.',
    price: 600,
    category: 'Others',
    imageUrl: getProductImage('Walnuts (Akhrot)', 'Others'),
    unit: '250g',
    stock: 30,
    isOrganic: false,
  },
  {
    name: 'Pistachios',
    description: 'Roasted and salted premium pistachios.',
    price: 400,
    category: 'Others',
    imageUrl: getProductImage('Pistachios', 'Others'),
    unit: '250g',
    stock: 45,
    isOrganic: false,
  },
  {
    name: 'Dates (Khajoor)',
    description: 'Sweet and soft premium quality dates.',
    price: 250,
    category: 'Others',
    imageUrl: getProductImage('Dates (Khajoor)', 'Others'),
    unit: '500g',
    stock: 60,
    isOrganic: false,
  },
  {
    name: 'Organic Jaggery',
    description: 'Pure and chemical-free organic jaggery.',
    price: 80,
    category: 'Others',
    imageUrl: getProductImage('Organic Jaggery', 'Others'),
    unit: '1 kg',
    stock: 70,
    isOrganic: true,
  },
  {
    name: 'Cold Pressed Coconut Oil',
    description: 'Pure and natural cold-pressed coconut oil.',
    price: 350,
    category: 'Others',
    imageUrl: getProductImage('Cold Pressed Coconut Oil', 'Others'),
    unit: '500ml',
    stock: 40,
    isOrganic: true,
  },
  {
    name: 'Pink Himalayan Salt',
    description: 'Natural and mineral-rich pink Himalayan salt.',
    price: 120,
    category: 'Others',
    imageUrl: getProductImage('Pink Himalayan Salt', 'Others'),
    unit: '1 kg',
    stock: 100,
    isOrganic: false,
  }
];

export const TELANGANA_CITIES = [
  'Hyderabad',
  'Warangal',
  'Nizamabad',
  'Khammam',
  'Karimnagar',
  'Ramagundam',
  'Mahbubnagar',
  'Nalgonda',
  'Adilabad',
  'Suryapet'
];
